apiVersion: v1
kind: Service
metadata:
  name: redis-app-service
spec:
  selector:
    app: redis-app
  ports:
    - protocol: TCP
      name: app
      port: 8080
      targetPort: 8080 # containerPort
    - protocol: TCP
      name: redis
      port: 6379
      targetPort: 6379
  type: LoadBalancer